apiVersion: v1 
kind: Service 
metadata:
   name: rtp 
   namespace: valaxy 
spec:
  type: NodePort 
  selector: 
    app: rtp 
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000 
      